install.py

restore: tell user to remove install media before we reboot

---

backend.py
repository.py

Stumbled on this while reading the code

repository: remove unused "mount" parameter from getBranding

---

netinterface.py
netutil.py

Now only RH Style are used so this code can be removed 
Solves: https://github.com/xenserver/host-installer/issues/46

Maintenance: remove dead code of DebStyleInterface

---

backend.py
disktools.py
repository.py

To support XS9, there are some updates:
* Update sfdisk command line
* Update yum to dnf
* Setup a new rpm group for test purpose
* Remove history_record and default to true The new rpm group may be revertted when we got all package ready

CP-44556: Support xs9

---

disktools.py

During installation/upgrade we remove all partitions and then create new partitions as required. This is done also for partitions that needs to be preserved (like Dell utility partition).
By default partition utilities tries to align start of the partitions for better performance but this causes partitions with data to be recreated with different start/end corrupting them.
To avoid the corruption do the alignment from our code when we create new partitions and avoid alignment done in the utilities (adding `--set-alignment=1` parameter).
As a minor change create a single command to create and setup a single partition instead of using multiple commands.
This is just a verbatim port of https://github.com/xenserver/host-installer/pull/81 to the `master` branch.

CA-384621: Do not move partition to preserve data

---

constants.py
disktools.py

Minor partitioning improvements

---

disktools.py
diskutil.py

Include mmcblk-devices in disk selection

---

backend.py

XS8 version of https://github.com/xenserver/host-installer/pull/90

CP-37929: Remove legacy logrotate mechanism (XS8)

---

upgrade.py

In versions prior to XS 8.4, the net-snmp rpm already existed, but we did not declare to support this feature. Now in XS 8.4 we have enhanced this feature and will officially release it. XS 8.4 is the first version to support the SNMP feature. The host-installer is modified here to automatically back up and restore the corresponding configuration files when RPU to future versions. Versions prior to 8.4 do not require backup and restoration.

CP-44441: Restore SNMP service config

---

answerfile.py

Although maybe it lost some value I think the author meant deprecated.

Fix typo in comment (depreciated -> deprecated) - TRIVIAL

---

answerfile.py
backend.py
constants.py
disktools.py
diskutil.py
doc/answerfile.txt
doc/features.txt
tui/installer/__init__.py
tui/installer/screens.py

Merge of 4kn feature branch:
- Detect disks with block size greater than 512 bytes
- Name of SR type capable of using such disks is specified in a feature file.
- Require such an SR type be used if available and required given the disks to use for storage.
- Expectations for such an SR type documented in doc/features.txt

CP-45747 / CP-47742 4kn merge

---

install.py

Filter secrets and sensitive data from the results/answer dictionary during failures
Will produce a follow up PR for release/xs8

CA-389160: Filter sensitive data during failures

---

install.py

Filter secrets and sensitive data from the results/answer dictionary during failures

CA-389160: Filter sensitive data during failures - XS8

---

upgrade.py

Fixup preserve pool certificates across upgrades

---

backend.py

CP-47625: Replace mkinitrd with dracut command
dracut has been upgraded and mkinitrd command has been obsoluted
Update to use dracut to generate initrd
mkinitrd does not has `--latch` option, even in XS8,
and `/etc/dracut.conf.d` is always exists as dracut package
install and own the folder.
Also clean the dead code in the else branch
See job: 3977688 install succeed

CP-47625: Replace mkinitrd with dracut command

---

netutil.py

Fix comment indentation.
Reduce indentation (easier to see difference without space changes).

Minor space changes

---

backend.py

This is a backport of #125 to xs8

[XS8] setEfiBootEntry: make error messages more useful

---

repository.py

DNF output is a bit different from YUM causing the progress bar to not be updated while installing packages.
Update code parsing command output.

CA-392421: Support DNF output parsing correctly

---

disktools.py

Instead of calling sgdisk for each partition call it with a single command with all partitions.
This makes the operation more atomic and make it faster.

Repartition with one single command

---

startup/preinit

Shorter and not requiring changes between Python 2 and 3.

Use xl command instead of small inline python

---

Makefile
bootloader/grub-usb.patch

[xs8 backport] Provide a Makefile for installation

---

upgrade.py

OpenSSH package is upgraded to 9.8p1 which restricts host key /etc/ssh/ssh_host_*_key mode and group attributes. Thus add this commit to support converting these attributes during RPU. Test job 4107637 passed.

CP-50298: Support restoring dir to specified mode and user/group attributes

---

upgrade.py

This is a backport of #154 to xs8, including cherry-picking of part of the work already included there.

[XS8] preserve stunnel certs

---

upgrade.py

No reason to store the list in the upgrade object.

Change buildRestoreList to return list of files

---

backend.py

Allows to exclude some partitions from the layout.

Dynamically compute layout string based on partition availability

---

init

Increase the timeout to 120 seconds, this align with systemd default value

CA-404297: Should not bring up extra interfaces

---

upgrade.py

attributes
Signed-off-by: Deli Zhang <deli.zhang@citrix.com>
(cherry picked from commit 0ccfe46d281a0b36d612a08120290b5288cd924c)

CP-50298: Support restoring dir to specified mode and user/group

---

backend.py

This reverts commit 86347fce31416426f0598391e8d5313afbc26c5f
The code change would cause TCNSSdxXSUpgrade test cause failure. Revert this commit first. Make clear Netscalar host installation requirements and then change host-installer accordingly.

revert "CA-400058: fix preserve-first-partition installation"

---

repository.py

Output from DNF 5 is a bit different, specifically:
- progress is reported to standard error;
- package installation progress has numbers at the beginning.

Support DNF 5 output

---

Makefile

[XS8] Makefile: give more flexibility to select base multipath.conf

---

doc/parameters.txt

[XS8] doc/answerfile: clarify and fix description of --network_device

---

backend.py

[XS8] __mkinitrd: pass -f to dracut

---

repository.py

- migrate `yum` command to `dnf`
- `dnf group info` output format updated, change to use `dnf group list` instead

CA-411987: Migrate dnf group `driver` check from yum to dnf

---

tui/installer/screens.py

We should check variant selection for each driver in case of users' mistake operations which deselect variant for some drivers.

CA-413008: fix variant selection bug

---

upgrade.py

[XS8] upgrade: restore saved firewall-port plugin state

---

tui/installer/screens.py

Use SKIP_SCREEN so that pressing back doesn't immeidately go forwards again.

CA-417508: Fix pressing back from EUA

---

backend.py

CA-411898: turn off retbleed for disk throughputs
