cpiofile.py
Commit bc9a0551cad0 ("CP-40676: Convert cpiofile.py to UTF-8") changed cpiofile.py to UTF-8 but didn't specify the encoding. This is needed for Python 2.x which doesn't default to UTF-8 (unlike Python 3.x).
Fixes: bc9a0551cad0 ("CP-40676: Convert cpiofile.py to UTF-8")
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
=> CP-40676: Specify utf-8 encoding explicitly

doc/parameters.txt, init
Booting the installer with `answerfile=URL` and no `install` to
complement it would just get no effect, with just a cryptic "No
operation specified for answerfile" hidden in the logfile.
The `install` parameter had only one use in the current code: allowing
`answerfile` to be honored, so just ignore it.
=> init: allow 'answerfile' to work without 'install' boot parameter

doc/parameters.txt
Try to make it more obvious how to use them, especially installer parameters as they need to be specified on the boot command line without their prefixing dashes.
Signed-off-by: Samuel Verschelde <stormi-xcp@ylix.fr>
=> Document the use of startup and installer parameters

backend.py, product.py
Get `xen-pciback.hide` from a host's kernel's args 
Give it to the bootloader after the upgrade
This allow a user to keep it's PCI passthrough after an upgrade
Signed-off-by: BenjiReis <benjamin.reis@vates.fr>
=> Keep `xen-pciback.hide` when upgrading

backend.py
When removing UEFI boot entries during an install or upgrade, the old entry label may be any of the previous version labels so keep a list and match against the list. Also include the current version name in the list so that self-upgrades always work.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
=> CP-41369: Match Citrix Hypervisor when removing UEFI boot entry

backend.py
If CONFIG_EFI_VARS is enabled, efibootmgr is able to use that deprecated interface when inside a chroot. With newer kernels where that interface is removed completely [1], it requires bind mounting efivarfs at the correct path so that efibootmgr works inside a chroot.
[1] 0f5b2c69a4cb - efi: vars: Remove deprecated 'efivars' sysfs interface
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
=> CA-375063: Mount efivarfs when calling efibootmgr

answerfile.py, backend.py, doc/answerfile.txt, product.py, tui/installer/screens.py
Clearing up time settings during install
New settings appear like this when using DHCP IP:
Which leads to a new manual time setting screen like this:
The manual NTP server entry has also be stripped down to just entry of the servers (automatically enabled) - I forgot to grab a picture, let me know if you want to see it
New settings when using static IP:
=> CA-369899: NTP Server options, DHCP|Default|Manual|None

util.py
When answers are dumped to log, URL sources in extra-repos were serialized in a non-human-readable way.  This allows to get the URL printed instead of an opaque object description.
=> util.URL: implement missing bits for extra-repos

answerfile.py
Refactor the logic in answerfile.py for `parseTimeConfig` - it needs to be able to access the results from `parseInterface` to determine the resulting NTP configuration (specifically it needs to access `net-admin-configuration` to determine if DHCP is configured), and as such cannot simply return updates to `results`, it needs to have the current dictionary.
=> CA-380626: Fix issue with NTP logic and unattended installs

product.py, tui/installer/__init__.py
This covers the case where we have a management interface (mgmt_iface) from /etc/xensource-inventory but we can't find networkd.db in the installation (in the case where we've started an install/upgrade but it was interrupted)
net-admin-bridge or net-admin-interface is required by performInstallation, the failure if they are missing is abstract and unhelpful, this change will fail earlier and more clearly
=> CP-43949: Raise exception when we can't find networkd.db

backend.py, product.py
If a user set the `sched-gran` [through XAPI](https://github.com/xapi-project/xen-api/blob/master/ocaml/xapi/xapi_host.mli#L524), the settings should be preserved after a host upgrade.
Signed-off-by: BenjiReis <benjamin.reis@vates.fr>
=> Keep `sched-gran`grub entry upon upgrade

backend.py
This allows Secure Boot to work. It also works for the non-Secure Boot path - any verification errors would simply be ignored.
=> CP-45668: Boot shim instead of grub

tui/installer/screens.py
XS9 installation failed due to *cmp* is used as *cmp* is only available in python2 while XS9 is based on python3
=> CA-384265: Remove use of cmp to fix XS9 installation

product.py
Previously any exceptions which occurred were silently suppressed, instead log such occurrences to enable easier debugging from the installer log.
=> XSI-1498: Log any exceptions parsing existing bootloader config

constants.py, product.py
Previously we were not setting `ntp-config-method` when parsing the NTP configuration from an old version, resulting in any NTP servers that were read being ignored.
Set the appropriate `ntp-config-method`, and also filter out any 'default' NTP servers from the `ntp-servers` list so we only load customer specified servers. Note this is done using a fixed list of default domains, as this has changed in the past and may change in future, so cannot be read from the current release config.
=> CA-385350 Fix handling of NTP configuration over upgrade

disktools.py
During installation/upgrade we remove all partitions and then create new partitions as required. This is done also for partitions that needs to be preserved (like Dell utility partition).
By default partition utilities tries to align start of the partitions for better performance but this causes partitions with data to be recreated with different start/end corrupting them.
To avoid the corruption do the alignment from our code when we create new partitions and avoid alignment done in the utilities (adding `--set-alignment=1` parameter).
As a minor change create a single command to create and setup a single partition instead of using multiple commands.
=> CA-384621: Do not move partition to preserve data

backend.py, disktools.py, diskutil.py, install.py, product.py
By default in Python 3 a division, even between integers, is done using floating point. This causes the result to be float and potentially reduce precision (float precision is 52 bits).
To avoid changes in behaviour between Python 2 and Python 3 and possible precision losses use explicit integer divisions that will produce same results.
=> Use explicit integer division where necessary

startup/depmod.conf
This old depmod.conf is the default in el7, the fix was made upstream in rhel years ago.
Also drop its companion systemd hook to run `depmod -a`.
=> Drop depmod config files

disktools.py, diskutil.py
This is a small patch we're carrying in xcp-ng for some time, essentially useful to people installing in their home labs.
=> Include mmcblk-devices in disk selection

backend.py, cpiofile.py, repository.py, upgrade.py
This change reduces the difference between Python2 and Python3 making easier to cherry pick or rebase commits from a branch to another.
=> Use constant octal syntax compatible with Python3

backend.py, diskutil.py, product.py, report.py, restore.py, tui/installer/screens.py
This change allows to restore SDX machines updated to XenServer 8.
SDX still uses MBR and 3 partition schema (plus one possible utility partition). 
The possibility to restore this schema was removed from installer time ago but we need to add back to support restore of SDX products.
After restoring backup data to logs (which used to be the root partition) all additional partitions (EFI boot, swap, logs) not necessary are removed, backup recreated and partition schema is moved from GPT to MBR.
This PR is based on https://github.com/xenserver/host-installer/pull/89 (which contain base improves).
Opened as Draft as I don't like some aspect of it. Maybe just paranoia:
- clearing "manually" the GPT after `sfdisk`... but wiping every entirely before open a window for loosing data which is …
=> Allows to restore really old layout used by NetScaler SDX machines

disktools.py
partitions has always at least one elements (a dummy None one) so if can't have a length of 0.
=> Remove useless check - TRIVIAL

disktools.py
The size of GPT used sector depends on sector size.
Specifically it takes 1 sector for the header and others for partition table.
Tested with emulated disk using Qemu and 4KB disk.
=> Fix sector computation for disk with sector size not 512

backend.py, diskutil.py, product.py, report.py, restore.py, tui/installer/screens.py
This series is a preparation before adding support for restoring some old systems from backup.
Changes:
- rename confusing `inspectTargetDisk` and added a comment;
- `probeDisk` returns a new object to make easier to update and add results;
- removed unused parameter from `probeDisk`;
- add `swap` result to `probeDisk`.
See commit messages for details.
=> Minor changes to inspectTargetDisk and probeDisk

tui/installer/__init__.py, tui/installer/screens.py
If the warning is shown, it will be shown after agreeing to the EUA.
This is what it looks like:
=> CP-47538: Deprecate legacy BIOS boot

upgrade.py
Otherwise members cannot establish connection to the coordinator after an RPU
There's a decision to be made for user-installed certificates, which are used to connect to appliances. But this functionality has long worked like that, so I'd rather not upset the balance
=> Preserve pool certificates across RPUs

backend.py
According to https://www.freedesktop.org/software/systemd/man/latest/hostname.html Systemd set hostname with following sequence
- kernel parameter, systemd.hostname
- static hostname in /etc/hostname
- transient hostname like DHCP
- localhost at systemd compile time
Set static hostname `localhost.localdomain` in /etc/hostname prevents obtain hostname from DHCP, and all XenRT installed host got localhost.localdomain as the hostname
This commit set empty static hostname to permit DHCP
=> CP-47621: Enable ability to set hostname from DHCP

scripts.py
In XS 9 python2 is removed, python is just python3 link. Also remain python interpreter (in shebang) will keep compatibility for scripts, e.g. revert-bootloader.py generated by host-upgrade-plugin for both XS 9 and XS 8.
=> CP-48077: Support python interpreter in shebang of env

constants.py, test/test_errors.py
Avoids duplication of part of the error messages.
Do not declare enumeration or dictionary, just use strings.
Make sure error is terminated with a dot.
This is intended to supersedes https://github.com/xenserver/host-installer/pull/80.
=> Rewrite error_string function

backend.py
Fix RuntimeError: dictionary changed size during iteration by creating a copy of the keys using list()
=> Fix RuntimeError: dictionary changed size during iteration

backend.py
* CP-45668: Boot shim instead of grub
This allows Secure Boot to work. It also works for the non-Secure Boot
path - any verification errors would simply be ignored.
* CP-47745: Detect EFI shim presence dynamically
Allows code to work with both secure boot or not.
=> Handle secure boot installations

backend.py
In case fallback initrd is used potentially the user wants to recover some situation (like some H/W changes) where it would be preferrable to have a more generic initrd with more drivers and software.
This used to be the case before the introduction of dracut usage so restore the old behavior.
=> CA-392333: Do not use host-only fallback initrd

disktools.py, restore.py, upgrade.py
Detect hidden flag and save when reading.
Write the flag when partitions are written.
Note that compared to the changes for master this add support for MBR restore (very old XS versions).
=> CA-391659: Preserve hidden flag updating GPT partitions

backend.py
There were 2 identical messages, making it hard to guess from a screenshot which exec caused an error.
While at it, the entry-removal code path can be executed more than once, so give a way to identify which entry is involved when the call fails.
=> setEfiBootEntry: make error messages more useful

backend.py
Each time, RPM execs a process during the install, it closes all open file descriptors up to the hard limit. The default hard limit for systemd services with newer systemd increased from 4096 to
524288. This caused a regression in installation time as dnf spends almost all the time setting the CLOEXEC bit on non-existent file descriptors.
Fix this by ensuring that /dev, /proc, and /sys are bind mounted into the root before starting installation. That way, RPM can close only the open file descriptors rather than all of the possible fds. This decreases the dnf phase of installation on my test host from 900 seconds to 100 seconds.
As a side effect, it silences various complaints about these filesystems not being mounted, simplifies the code, and avoids pointless mount/unmount cycles.
=> CA-389863: Speed up installation with newer systemd

answerfile.py, backend.py, cpiofile.py, disktools.py, diskutil.py, generalui.py, hardware.py, init, netutil.py, product.py, repository.py, restore.py, tui/installer/screens.py, tui/network.py, tui/repo.py, util.py, xelogging.py
This PR takes some changes from master branch.
The difference look smaller ignoring space changes.
1. Revert "Reuse context manager to mount directory for chroot executed commands"
This reverts commit 8390720f335cd6b6cfe4d4b86c1663bf9c664ea4.
Superseded by next commit on master
2. CA-389863: Speed up installation with newer systemd
Each time, RPM execs a process during the install, it closes all open file descriptors up to the hard limit. The default hard limit for systemd services with newer systemd increased from 4096 to 524288. This caused a regression in installation time as dnf spends almost all the time setting the CLOEXEC bit on non-existent file descriptors.
Fix this by ensuring that /dev, /proc, and /sys are bind mounted into the root before starting installation. That way, RPM …
=> Some sync master -> release/xs8

disktools.py
`sfdisk` is always returning 512.
Device mapper code assumes 512.
Use always `blockdev --getss` to get the correct value.
=> Use blockdev command to read sector size

backend.py, constants.py, disktools.py, test/test_errors.py
1. CP-45668: Boot shim instead of grub
This allows Secure Boot to work. It also works for the non-Secure Boot path - any verification errors would simply be ignored.
2. CP-47745: Detect EFI shim presence dynamically
Allows code to work with both secure boot or not.
3. Rewrite `error_string` function
Avoids duplication of part of the error messages.
Do not declare enumeration or dictionary, just use strings.
Make sure error is terminated with a dot.
4. Add a test for `error_string` function
5. Remove useless check
partitions has always at least one elements (a dummy None one) so it can't have a length of 0.
6. Fix sector computation for disk with sector size not 512
The size of GPT used sector depends on sector size.
Specifically it takes 1 sector for the header and others for partition …
=> Port some commits from master to release/xs8

backend.py, cpiofile.py, disktools.py, diskutil.py, fcoeutil.py, init, init_constants.py, install.py, netutil.py, repository.py, tui/fcoe.py, tui/installer/screens.py, tui/network.py, tui/repo.py, upgrade.py, util.py
Use different ways to reduce differences between the 2 branches
1. Make print statements Python 2/3 compatible
Add parenthesis where possible, use `import __future__` to get full source compatibility in Python 2.
2. Use universal_newlines option for Popen
The options is supported by Python 2 too, not only Python 3
3. Force list in some cases
Python 3 tends to use generators which in some cases changes the results, or simply you want to have a list instead.
Python 3 code already has this change, in Python 2 is mainly a no-operation so copy to Python 2 to reduce source differences.
4. Use range and items to increase Python 2/3 compatibility
The difference between xrange vs range and items vs iteritems in Python 2 mainly changes list with iterators.
This could improve memory usage and …
=> Reduce difference between master and release/xs8 branches

shrinklvm.py
Trying to shrink LVM partition if we detect that we don't need to do anything we returned without closing lvm object. As lvm object is retained by VG objects contained in the same lvm object, the release (and the close of the internal "file" attribute) happens when a full garbage collection is done (due to the circular reference).
Close manually to release the device as soon as possible making the following device partitioning succeed.
=> CA-392935: Release device if partition does not need to be resized

disktools.py
This fixes a regression introduced by commit 99bec34bfc "CA-391027: Mount devices specified by mount= only when needed", code was always attempting to create the directory before mounting.
The call to `os.makedirs` do not use `exists_ok` option for compatibility with Python 2 code.
=> CA-392916: Create directory for mount= option

diskutil.py
Previously, the installer asserted that both the Block Valid and Firmware Boot Selected flags were set. On some machines, the Firmware Boot Selected flag is not set.
It is not clear why the installer checks this flag. The spec doesn't define its meaning and other software doesn't seem to check it. The only reference I could find was in iPXE where it is unconditionally set. Therefore, simply ignore the flag.
At the same time, instead of hitting an assertion error if the iBFT block is not marked as valid, just skip it. This allows the installation to continue.
=> CA-392758: Remove Firmware Boot Selected flag check

diskutil.py
Previously, the installer asserted that both the Block Valid and Firmware Boot Selected flags were set. On some machines, the Firmware Boot Selected flag is not set.
It is not clear why the installer checks this flag. The spec doesn't define its meaning and other software doesn't seem to check it. The only reference I could find was in iPXE where it is unconditionally set. Therefore, simply ignore the flag.
At the same time, instead of hitting an assertion error if the iBFT block is not marked as valid, just skip it. This allows the installation to continue.
=> Backport fix for CA-392758

backend.py
This allows to install a clean XenServer 8 using NetScaler platform machines based on MBR partution layout.
=> CP-49195: Allows to preserve first partition from MBR layout

disktools.py
Code to handle `mount=` options were rewritten adding additional error checking.
However this resulted in a feature regression as this poor error handling is used as a "try next if fails" behavior allowing to specify multiple devices for the same mount point. For instance specifying `mount=/dev/sda2:/mnt mount=/dev/disk/by-label/DEMO:/mnt` for the same `/mnt` mount point the two possible device names were attempted. So instead of giving error log the error and continue to restore the old behavior.
=> CP-49641: Ignore errors mounting/unmounting explicit mount points

startup/preinit
Shorter and not requiring changes between Python 2 and 3.
This patch is already in `master`, porting to `release/xs8`.
=> Use xl command instead of small inline python

disktools.py
Old installers do not properly clear GPT data while updating MBR partitions. Note that as SDX has a partition to preserve, partitions are updated even on clean installation. New installer currently does not like having partial GPT data throwing an error. Note that kernel is instead perfectly fine, ignoring invalid GPT data and only considering MBR. Fix the installer to support such situation.
=> CA-393429: Fix upgrade to XS8 from downgraded SDX MBR installation

constants.py, disktools.py
The behavior of gdisk if disk layout cannot be updated is different from fdisk; the former write a warning while the latter returns with error.
This results in possible corruptions during the installation. Check and report the warning as error.
=> CA-392317: Make sure kernel is up to date using Gdisk

Makefile, bootloader/grub-usb.patch
Reasons to have this here include:
* don't require changes to srpm when the set of installed files change
* make installer development faster by deploying directly to a filesystem
This installation process still depends by default on the sm package being installed, but through SM_ROOT variable it can now be run on a dev machine where this is not the case, it just needs an unpacked version of the package.
Matching change for SRPM: https://github.com/xcp-ng-rpms/host-installer/commits/makefile
=> Provide a Makefile for installation

Makefile, disktools.py, ppexpect.py, test/test_ppexpect.py
If a disk have partial GPT data corrupted (this can result from an initial usage of GPT followed by some MBR tool usage not cleaning properly GPT) Linux kernel will handle correctly the disk using MBR data but `(s)gdisk` (and so our installer) will complain.
This can be an issue even with clean installations if we need to preserve a partition.
Use interactive `gdisk` which has an option to consider only MBR data in this case.
The `pexpect` replacement is there to avoid an additional dependency.
=> Handle corrupted GPT data with MBR disks

Makefile
`master` branch has no such files so backporting the commit from `master` caused these to be missing.
=> Copy missing files during "make install"

upgrade.py
When upgrading from 8.3 or later the certificates generated on first boot need to be preserved.  This impacts reinstallation by "upgrading to itself" an existing xcpng-8.3 or xs8.
This completes d74565a5c81b49f2056affb2684d62c22a9d951a and 6d9e2db000685789d9aa2076b2eedde544494122, after which joining a pool with an upgrading master otherwise shows:
The server failed to handle your request, due to an internal error. The given message may give details useful for debugging the problem.
message: Sys_error("/etc/stunnel/certs/sdn-controller-ca.pem: No such file or directory")
=> Preserve more stunnel certificates on upgrade

disktools.py
Commit 6495353cce6a ("CA-392317: Make sure kernel is up to date using Gdisk") added a check to ensure that issues with rereading the partition table are detected. However, rereading the partition table always fails when device-mapper is used (BLKRRPART returns EINVAL) which causes spurious installation failures. The host installer correctly uses kpartx to recreate partitions after repartitioning device-mapper devices so simply ignore the warning from sgdisk when using device-mapper.
=> CA-395582: Fix installation with multipath enabled

answerfile.py, backend.py, constants.py, disktools.py, diskutil.py, doc/answerfile.txt, doc/features.txt, tui/installer/__init__.py, tui/installer/screens.py
This is a cherry pick of the commits in https://github.com/xenserver/host-installer/pull/105. I probably should have done that at the time. Apart from fixing some superficial conflicts, the changes here relative to that PR are the use of the print function rather than print statements, and the use of int rather than long to cast floats.
=> CP-50361 Port 4kn changes from xs8 branch

restore.py
setEfiBootEntry called here: https://github.com/xenserver/host-installer/blob/master/restore.py#L134
Which requires `mounts['esp']`: https://github.com/xenserver/host-installer/blob/master/backend.py#L1136
Manually tested this fixes the regression
```
INFO     [2024-07-26 13:23:01] Traceback (most recent call last):
File "/opt/xensource/installer/install.py", line 256, in go
restore.restoreFromBackup(backup, progress)
File "/opt/xensource/installer/restore.py", line 143, in restoreFromBackup
backend.setEfiBootEntry(mounts, disk, boot_partnum, constants.INSTALL_TYPE_RESTORE, branding)
File "/opt/xensource/installer/backend.py", line 1142, in setEfiBootEntry
if os.path.exists(os.path.join(mounts['esp'], 'EFI/xenserver/shimx64.efi')):
~~~~~~^^^^^^^
KeyError: 'esp'
```
=> `restore.py`/`restoreFromBackup()`: Ensure esp mount point is known before setting EFI boot entries

restore.py
This is a backport of https://github.com/xenserver/host-installer/commit/5e10dc739750d3d9922768fde2b287c93f2f6c8e
`mounts['esp']` is required when calling `setEfiBootEntry` with UEFI systems
Fixes https://github.com/xenserver/host-installer/issues/150
=> XS8: Ensure esp mount point is known before setting EFI boot entries

answerfile.py, backend.py, constants.py, diskutil.py, doc/answerfile.txt, install.py, product.py, restore.py, upgrade.py
Add support for EXT4 root and logs partitions on fresh install and upgrade.
Backup and restore is handled by checking the type of the partition being backed-up/restored-to instead of assuming it's EXT3.
This change is intentionally undocumented in doc/answerfile.txt as we are not expecting to support environments which intentionally divert from the default fs type.
This has been tested manually in all ext3/ext4 combinations (e.g. from ext3->ext3, ext3->ext4, etc.) in fresh installs, upgrades, and restores.
A regression test is being introduced into XenRT, see jobs 4087565 & 4088336 and XenRT PR XXX
This PR depends on commit e72687b44b5968aa275f01a44c112e95a28121fb from https://github.com/xenserver/host-installer/pull/161
For XenServer internal, see PRs:
grub.spec - PR 23 …
=> IH-416: EXT4 for Dom0 Root & Logs Partitions

backend.py
`partitionTargetDisk` returns a tuple with boot mode and all partition numbers. Sort the returned partitions based on expected order.
No change in functionality.
=> Use partition numbers to sort partitionTargetDisk output

constants.py, upgrade.py
That name was used in 2012, probably version 5.
=> Remove support for very old Xapi DB name

disktools.py
The name is currently misleading.
=> Add a comment for ID_LINUX partition GUID

answerfile.py, backend.py, disktools.py, upgrade.py
These machines have limited disk space, change layout.
=> Add support for SDX 8900 platform

upgrade.py
It was not clear the offset.
This will allow to easily avoid some partitions if needed.
Also, is more similar to `writeDom0DiskPartitions` in `backend.py`.
=> Simplify partition order computation upgrading partition schema

upgrade.py
If the backup is done into the temporary directory we don't be able to use it on failure so don't do it.
This also fixes a problem of failure doing such backup; this occurred in an installation with backup GPT correct but invalid primary GPT.
=> CA-403412: Do not backup GPT layout on temporary directory

disktools.py, diskutil.py, restore.py
The particular issue turned out to be that the nested UEFI host being restored had several disks attached.  Since this is done as NVMe namespaces of a single disk, all sharing the same ID, udev in dom0 does not have enough info and messes up /dev/disk/by-id/ on which restore relies because of `/etc/xensource-inventory`:
```
lrwxrwxrwx 1 root root 13 Jul 15 14:28 nvme-QEMU_NVMe_Ctrl_nvme0 -> ../../nvme0n3
lrwxrwxrwx 1 root root 15 Jul 15 14:28 nvme-QEMU_NVMe_Ctrl_nvme0-part1 -> ../../nvme0n2p1
lrwxrwxrwx 1 root root 15 Jul 15 14:28 nvme-QEMU_NVMe_Ctrl_nvme0-part2 -> ../../nvme0n1p2
```
Only the addition of the `tool.dump()` call allowed me to connect the "Failed to create root filesystem" error with that longstanding (in)famous issue, but a few other additions were useful to get there.
=> Enhance tracing to hunt for restore bug

Makefile
The copy in sm is being removed in favour of deploying it directly from device-mapper-multipath, so we need to pull the 'real' installed copy rather than relying on the alternatives location sm used to use.
=> CA-405458: Pull the installed multipath.conf, rather than a copy in sm

backend.py
memtest86+ is updated to install the kernel into /boot This commit add a conresponding grub menu to load the kernel
=> CP-53300: Add 'Memtest86+ (UEFI)' boot menu

backend.py
if preserve-first-partition is yes in answer file, then installer fails with an IndexError because it tries to access a partition which does not exist
simulate the installation failure, and we get error message as follows,
"Installation failed on !genus-34-67d: RuntimeError: Installer only supports a single Utility Partition at partition 1, but there is no Utility Partitions"
=> CA-400058: fix preserve-first-partition installation

netutil.py
The call to systemd-networkd-wait-online waits for all managed links' operational state to be higher than "degraded" (i.e. "enslaved" or "routable"). Effectively, this means that the link has a routable address.
In some situations, the link gets an IPv6 link-local address at which point it is considered "online". This causes a race condition and intermittent failures when doing automated installs that require an IPv4 address but the interface does not yet have an IPv4 address yet (e.g. because of a slow DHCP server).
Fix this by requring an IPv4 address for the link to be considered up. This will need to be reworked in the future when XenServer fully supports IPv6 in the installer.
=> CA-404794: Require an IPv4 address for the network to be up

backend.py
xcp/bootloader.py/readGrub2 parses the kernel args for each entries in grub.cfg: 
```
elif l.startswith("linux"):
kernel, kernel_args = (l.split(None, 1)
[1].split(None, 1))
```
Missing args will result in an error.
Added args to make it the same as in XS9 host:/boot/efi/EFi/xenserver/grub.cfg
+++++++++++++++++++++++++++
Updated:
Removed invalid arguments from memtest86+, and raised another PR to handle the case of an entry with no additional arguments
=> CA-407115: Remove invalid arguments from memtest86+

repository.py
DNF parses strings a bit differently from YUM.
Quote according, allowing to have spaces, backslashes and double quotes inside the string. This is especially useful for passwords.
=> CA-405400: Quote username and password in yum configuration

disktools.py
Newer fdisk output is different potentially causing installer to fail and exit if the disk is still partitioned with MBR schema. This is unlikely but handle it to be able to reinstall a system with such partitioning.
=> CA-408187: Parse correctly fdisk output

backend.py
Users get hit by DHCP hostname setting not working on versions 10.x too.
See e.g. https://xcp-ng.org/forum/topic/10414/static-hostname-overriding-dhcp-assigned-hostname
=> [XS8] Backport DHCP hostname fix

doc/parameters.txt
This makes it much less painful to point users to the doc when explaining them how to use `sshpassword`.
=> doc/answerfile: clarify and fix description of --network_device

upgrade.py
It happens #154 missed a few things:
* an empty `/etc/stunnel/certs` dir would not be restored
* the bundle of `/etc/stunnel/certs` dir would not be restored either
=> Preserve even more stunnel certs on upgrade

doc/answerfile.txt
Make the optional attributes description immediately follow the mandatory ones, instead of getting inserted between ipv4 and ipv6 elements, where it just creates confusion.
=> doc/answerfile: reduce admin-interface confusion

repository.py
Specifically:
SyntaxWarning: invalid escape sequence '\d'
=> Remove warning in regular expression

repository.py, util.py
The second parameter for `add_password` is a partial URL, not a hostname. Setting just the hostname make the authentication apply only if using default port.
Compute a URL with schema and port information.
=> CA-408238: Support basic authentication to HTTP server with different port

restore.py
The variable was renamed in commit 25f4ee21759e3e
(cfr "IH-416, CP-31054, CP-31055: Optional EXT4 Support"). 
This was discovered thanks for instrumentation of Bernhard.
=> Correct name for renamed "fs_type" variable

backend.py
ucode=scan is now the default behaviour (enabled by config) so drop it from the command-line arguments.
=> CP-53418: Drop ucode argument from Xen command-line

backend.py
Specifically:
> backend.py:1307:33: error: Argument 1 to "replace" of "bytes" has incompatible type "str"; expected "Buffer" [arg-type]
> backend.py:1307:47: error: Argument 2 to "replace" of "bytes" has incompatible type "str"; expected "Buffer" [arg-type]
This was discovered thanks to instrumentation of Bernhard.
=> Fix bytes/string mismatch

repository.py
commit a5778b39d6ee combine stderr to stdout and log stdout prefixed with "DNF" for DNF5 support. This means stderr file is no longer used and always be empty.
Just clean the unused code
=> CP-54099: Clean unused stderr file for dnf

diskutil.py
getDiskDeviceSize may fail to find the correct disk size, which could lead to the Python default of None being returned - in turn causing larger issues later in the installer where a numeric type is expected.
Matches XS8 PR: https://github.com/xenserver/host-installer/pull/236
=> XS9: XSI-1863: Use a disk size of zero if a disk size cannot be determined

upgrade.py
The two parameters are read from the xensource inventory so no need to pass them as parameters of the prepareUpgrade function.
=> Remove unused parameters passed to prepareUpgrade

backend.py
The management interface information is maintained by networkd host-installer just give up writing this information and networkd will maintain and write that information
=> CP-53840: Do not write mgmt interface info in xensource-inventory

backend.py, bootloader/grub-usb.patch, bootloader/grub.cfg
xen.pe is the new Secure Boot-enabled and signed Xen binary.
=> CA-402028: Boot xen.pe rather than xen.gz

backend.py
Due to missing initialisation during a manual upgrade the installer was failing due to missing key in "answers" dictionary. Provides the missing default to avoid the missing key.
=> XSI-1887: Fix upgrade

backend.py, bootloader/grub-usb.patch, bootloader/grub.cfg
Following an internal discussion, it was decided to use the `xen.efi` name instead of `xen.pe` name.
`efi` extension is the usual extension for EFI applications. `xen.efi` name is the official file name used by upstream Xen. Although currently the file is slightly different from the `xen.efi` use the same name.
Tested building a full ISO and doing manual install.
=> CP-307868: Boot xen.efi rather than xen.pe

tui/network.py
Previous the interfaces are renamed as ethX, thus X is used to order and display the interfaces.
Now the interface names are decided by kernel/systemd, so just order the interface by its name
=> CA-410647: Displaying select network interface should order by name

disktools.py, diskutil.py, restore.py
This is a "backport" of #155 to XS8, with one additional safety guard that does not apply to master any more (or more exactly, this is the original work on xs8 that let to the master PR)
=> [XS8] Enhance tracing to hunt for restore bug

disktools.py, diskutil.py
/dev/sda3#VG_XenStorage-54668b23-b850-6876-92c5-9228b5383e3d#11534336#915079692288#915075497984#218172#915095404032
After upgrading to lvm2-2.02.180-18.1.xs8.x86_64.rpm, the pv name becomes device link which is persistent path and is more appropriate to use, so change host installer to handle the case.
/dev/disk/by-id/scsi-36f4ee08067e880002df341f84273b684-part3#VG_XenStorage-54668b23-b850-6876-92c5-9228b5383e3d#11534336#915079692288#915075497984#218172#915095404032
=> CA-411085: Fix issue of pv name is device link

disktools.py, diskutil.py
The group 1 of `r'(.+)(p?|(-part))\d+$'` does maximum match incorrectly: 
input: scsi-36f4ee08074d4d5002e3ec9f12273e1c0-part3 
output: scsi-36f4ee08074d4d5002e3ec9f12273e1c0-part
Fix the issue, also verify if the disk of output exists.
=> CA-411650: Fix disk partition re bug

repository.py
Calling eject on a CD-ROM causes some udev rules to run. In some cases, the rules will poke /dev and race with the unmount of /dev in writeMachineId() and cause the unmount to fail with EBUSY. The failing unmount is ignored which ends up with /dev being mounted on /tmp/root twice causing the final unmount of /tmp/root to fail (because one instance of /dev is still bind-mounted). Fix this by settling udev after eject() so the system is in a clean state before continuing.
=> CA-410594: Settle udev after eject

disktools.py
The case3 re will match disk path e.g. /dev/nvme1n1 and /dev/disk/by-id/scsi-36f4ee08074d4d5002e3ec9f12273e1c0, so update it to avoid them.
=> CA-411650: Fix disk partition re issue for disk path

repository.py
Backport of https://github.com/xenserver/host-installer/pull/255
----
Calling eject on a CD-ROM causes some udev rules to run. In some cases, the rules will poke /dev and race with the unmount of /dev in writeMachineId() and cause the unmount to fail with EBUSY. The failing unmount is ignored which ends up with /dev being mounted on /tmp/root twice causing the final unmount of /tmp/root to fail (because one instance of /dev is still bind-mounted). Fix this by settling udev after eject() so the system is in a clean state before continuing.
=>  CA-410594: Settle udev after eject

backend.py
The previous PR (https://github.com/xenserver/host-installer/pull/198/files) for this improvement assumed that the first partitions are always utility partitions and was hence reverted after internal tests failed
There's no specification or requirement that the first partition is a utility partition, but there is an option (the default) to preserve the first partition if it is a utility partition. This was likely the cause of the confusion
=> CA-400058: Fail if there is no first partition to preserve when requested

backend.py
After installation, the following error occurred during startup.
/init: error while loading shared libraries:
libsystemd-core-257.2-5.xs9.so: cannot open shared object file:
No such file or directory
This problem is extremely difficult to reproduce, so added debug logs, and which will be reverted in future.
=> CA-412051: Add debug logs for libsystemd-core.so link issue

backend.py
There is hard code "eth" in converting interface name to bridge name. It is incorrect after dropping interface-rename. As host-installer needn't write management-interface to inventory any more (see https://github.com/xenserver/host-installer/pull/238), the net-admin-bridge generating code and related parameters can be removed.
=> CP-307931 Remove unused net-admin-interface key

diskutil.py, tui/installer/screens.py
Add a confirmation dialog to confirm when the user selects a disk that contain an SR since it may result in data being lost.
It applies to the primary disk selection and the guest disk selection.
At the same time, drop the code related to "target-is-sr" since it did determine whether the target is an SR but didn't do anything with the information.
The dialog looks like this:
=> CA-409830: Confirm when overwriting an SR

answerfile.py, backend.py, diskutil.py, product.py, restore.py, tui/installer/screens.py, util.py
Dependent on PR https://github.com/xenserver/host-installer/pull/248
=> CP-54461: SWRAID Upgrade & Restore

constants.py, doc/features.txt, tui/installer/screens.py
- Hide driver disk feature behind a feature flag
- Remove FCoE configuration from the welcome screen
Full FCoE removal will be completed in a follow-up.
=> CP-53110: Put driver disk feature behind a feature flag

restore.py
677583e7d0aefe57feb5506284ff4c608aec99dc changed the order of the partition numbers returned by backend.partitionTargetDisk
Although there is a comment saying it shouldn't be used for restore, it was already being used and we should update references to it when the original change was made.
Currently restore fails with fresh installations+upgrades as it confuses the primary partition with the backup partition, leading to an attempt to wipe a mounted partition
=> CA-414146: Fix restore partnum identification

answerfile.py, backend.py, install.py
Add a new answerfile label `<ssh-mode>on/off/auto</ssh-mode>` to control SSH auto-mode behavior and SSH service status:
- `<ssh-mode>on</ssh-mode>`: Disables auto-mode and enables SSH by default
- `<ssh-mode>off</ssh-mode>`: Disables auto-mode and disables SSH by default
- `<ssh-mode>auto</ssh-mode>`: Enables auto-mode and stops SSH once XAPI starts up
=> CP-308812 Add new Answerfile label ssh-mode to control SSH status

answerfile.py, backend.py, doc/answerfile.txt
During recovery a user may choose to re-install on a single physical disk while the other part of the SW RAID device is in-operable. To achieve this the answerfile must accept a "missing" second physical disk.
Performing upgrade & restore operations over a degraded device is not supported - this use case was requested by the internal customer as part of their reset process; in which a fresh installation will be performed on a single target device
=> CA-416618: Support degraded SW RAID installations
